### PR TITLE
Update for Julia 1.0

### PR DESCRIPTION
**Pull request by gabrielgellner**

### CODE REVIEW

**Comment by tkoolen** [comment]
Thanks very much. I'll make some changes to the `.travis.yml` file and submit a PR *against your PR* in a minute.

**Comment by tkoolen** [comment]
Ok, thanks for trying. I'll take a look this weekend.

**Comment by rdeits** [comment]
I don't think there's any need to worry about running that test on Windows. It's just there to ensure that the results we're producing are identical to the original fortran implementation, but it's sufficient to just test that on Linux/macOS, especially since we'll always have those tests run via Travis. @gabrielgellner I'll open a PR against your branch to disable that test on Windows

**Comment by rdeits** [comment]
thanks!

**Comment by tkoolen** [comment]
@rdeits, so I guess you also fixed the allocation issue, right?

**Comment by rdeits** [comment]
Yeah, it was in the fastview function: isbits -> isbitstype

**Pull request merged**
